### ISSUE TITLE
测速能不能支持从文件导入呢，例如gui-config.json? Feature Request

### ISSUE THREAD

**Issue by ghost** [mobier/shadowsocksr-speed#10]
SSR有大量节点，并不都是订阅链接的。能不能用SSR客户端的导出配置功能，例如导出的gui-config.json，包含所有节点的配置，检测并给出测试结果，哪些组中的哪些节点速度、是否失效？如果能根据节点延时大小排序，并给出推荐就更好了。

**Comment by mobier** [comment]
下个版本增加文件导入,现在就能对数据进行排序,现在是以youtube速度排序的,如果要修改成延时的话吧`self.x.sortby = "youtube"`修改为`self.x.sortby = "localPing"`,是否失效我判断的规则是用这个节点去访问网页,能访问成功的话表格中的`network`就是`success`
