### ISSUE TITLE
Windows上运行时，全部节点只有localping，没有测速，显示fail.

### ISSUE THREAD

**Issue by Nigel-NI** [mobier/shadowsocksr-speed#14]
![image](https://user-images.githubusercontent.com/23294384/50087676-d0bec500-023b-11e9-9a4e-1d6eb73daf59.png)
如图。此问题与https://github.com/mobier/shadowsocksr-speed/issues/11 中出现的问题相同。我尝试了文中列出的所有方法，但无一奏效。不过我注意到在切换节点时有大概三行文字一闪而过，但是速度太快，没法截屏下来。

**Comment by mobier** [comment]
我推测是程序权限问题,因为localping调用的是本地ping实现的,你试试直接用目录`win`下面的`ShadowsocksR-dotnet4.0.exe`能否正常使用

**Comment by Nigel-NI** [comment]
![image](https://user-images.githubusercontent.com/23294384/50089212-1c736d80-0240-11e9-9ad5-78f11431513a.png)
可以正常使用的。

**Comment by mobier** [comment]
emmm可以提供一下订阅链接吗我复现一下vxxwej@gmail.com

**Comment by Nigel-NI** [comment]
我不确定杀毒软件是否进行了干预，但我可以保证6665端口没有被占用。

**Comment by youngslim** [comment]
我是#11的, 当时问题解决是在internet属性-连接-局域网设置,打开应该是所有的都没有钩. 小飞机设置为紫色-也就是直连,代理模式是用户自定义. 供参考.

**Comment by Nigel-NI** [comment]
![image](https://user-images.githubusercontent.com/23294384/50228062-1fa65f00-03e2-11e9-9f02-fac50e7c3aec.png)
截下的一闪而过的提示

**Comment by mobier** [comment]
确定不是代理的问题吗.或者关闭防火墙试试

**Comment by Nigel-NI** [comment]
我用我同学的电脑试过了，出现了相同的问题。SSR可以打开谷歌，电脑已经关闭了杀毒软件和防火墙。
操作系统：Windows 10 64位 ( 版本号1803 )，Python版本 3.7.1
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37\lib\site-packages\socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
