### ISSUE TITLE
macos无法使用

### ISSUE THREAD

**Issue by nageshuizeii** [mobier/shadowsocksr-speed#16]
按照步骤安装的
![image](https://user-images.githubusercontent.com/16527235/50533740-84dd1b80-0b6b-11e9-8d5f-13611ba8b1a7.png)

**Comment by mobier** [comment]
pip3 install pyvirtualdisplay

**Comment by nageshuizeii** [comment]
你好，都安装了的，但是显示No module named 'pyvirtualdisplay'
![image](https://user-images.githubusercontent.com/16527235/50534709-9cbc9b80-0b7b-11e9-8247-463579e5a155.png)

**Comment by mobier** [comment]
sudo 试试,或者sudo pip3 install pyvirtualdisplay
