### ISSUE TITLE
关于win下上传下载速度测试结果为fail的问题，我已找到解决方法。

### ISSUE THREAD

**Issue by kingofotaku** [mobier/shadowsocksr-speed#18]
经过一番折腾我终于成功正常测试了。说一下我的做法：我先是用工具把整个master分支打包下载下来然后解压，在不对脚本和目录做任何改动的情况下直接运行脚本，然后就成功了（当然我发现杀毒软件的防火墙还是必须关闭，且包里带的ssr最好设置成直接连接，也就是紫色模式，这一点是参考之前那位成功的朋友的建议。），有这个问题的人可以试试。我用的git打包下载工具：[https://minhaskamal.github.io/DownGit/#/home](url)
![default](https://user-images.githubusercontent.com/12953574/52347290-8946ff00-2a5c-11e9-83f0-1bba02c1915e.PNG)

**Comment by Nigel-NI** [comment]
此方法解决了我的问题，感谢分享

**Comment by mobier** [comment]
emmmmm,是我win版本的模式没有改成直接连接模式的原因吗

**Comment by kingofotaku** [comment]
> emmmmm,是我win版本的模式没有改成直接连接模式的原因吗

我觉得更可能是有些人一开始只下了里面某几个脚本跑，然后就导致跑起来不正常（我一开始就是这样的，只下了win的脚本，结果发现缺东西就再补）

**Comment by 1072379816** [comment]
求教程，小白完全不知道怎么弄

**Comment by lu35548** [comment]
换成直连模式也还是全部FAIL..
