### ISSUE TITLE
Mac在sudo的最后一步报错

### ISSUE THREAD

**Issue by Upapanow** [mobier/shadowsocksr-speed#20]
MBP:shadowsocksr-speed $ sudo python3 shadowsocksr-speed.py
Password:
Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named `'requests'

**Comment by mobier** [comment]
pip3 install requests

**Comment by Upapanow** [comment]
已解决
