### ISSUE TITLE
Mac 无效

### ISSUE THREAD

**Issue by web0316** [mobier/shadowsocksr-speed#25]

**Comment by adslunk** [comment]
string argument should contain only ASCII characters

**Comment by mobier** [comment]
mac 测试过没问题的,可以提供一下错误的信息吗?

**Comment by woshizhd** [comment]
![Screen Shot 2019-04-16 at 1.12.52 PM.png](https://i.loli.net/2019/04/16/5cb5656b6f789.png)

**Comment by mobier** [comment]
@woshizhd 可以发我一下订阅链接吗?vxxwej@gmail.com,我查了一下,出现此错误的原因是目标网站的https证书不是在证书签发机构购买的。
