### ISSUE TITLE
大学生小白想问这些代码怎么用

### ISSUE THREAD

**Issue by 1072379816** [mobier/shadowsocksr-speed#26]
README.md不能完全看懂不知道怎么操作
我是windows
把master分支打包下载并进入程序目录 怎么操作
python shadowsocksr-speed_win.py gui-config.json(加上配置文件后不用输入订阅链接)，这些是输入字母然后空格隔开吗，配置文件是什么
最后这个url: //输入入SSR订阅链接，怎么弄

**Comment by mobier** [comment]
如果不知道配置文件是啥,就不用管了,SSR订阅链接都是用机场提供的,如果是自己搭的服务器也用不上这个工具吧

**Comment by 1072379816** [comment]
我是机场提供的。。。。这个代码是在python上面运行吗，还是在cmd上面。应该怎么输入，我试了一天都没成功

**Comment by 1072379816** [comment]
我是win10家庭版。这些代码的文件是要放在指定的目录里面吗

**Comment by mobier** [comment]
设置python环境变量,在CMD中输入python如果能进入控制台的话,退出来进入到程序目录执行`python shadowsocksr-speed_win.py gui-config.json`然后回车,成功的话终端会显示`url:`然后你吧订阅链接右键粘贴后回车即可

**Comment by 1072379816** [comment]
![image](https://user-images.githubusercontent.com/49575728/56079008-ff7f2d80-5e20-11e9-8120-0b5798d294d6.png)

**Comment by 1072379816** [comment]
哪里出错了？是不是输入python然后空格shadowsocksr-speed_win.py（这个文件）然后空格gui-config.json这个文件？这两个文件不在同一个目录里面

**Comment by 1072379816** [comment]
![image](https://user-images.githubusercontent.com/49575728/56079986-15471f80-5e2e-11e9-9a38-629ea580f3ed.png)
这是什么情况

**Comment by 1072379816** [comment]
T_T 想科学上个网不容易啊 T^T

**Comment by 1072379816** [comment]
进入到程序目录执行python shadowsocksr-speed_win.py gui-config.json，这一个步骤我不会操作

**Comment by mobier** [comment]
如果你可以尝试去百度一下错误提示的话你就不会如此的烦恼了`ModuleNotFoundError: No module named ‘requests’`,我把我百度到的在告诉你"原因：没有导入requests库"你需要`pip install requests`,最后希望你能学会自己解决问题,这样对以后的学习很大的帮助

**Comment by 1072379816** [comment]
![image](https://user-images.githubusercontent.com/49575728/56080822-5ba17c00-5e38-11e9-8ec7-25b7747ccdd8.png)
我把单独的文件都移进了win那个文件夹了然后出现这种情况。请问我解压zip之后是不是不能动文件的位置？还是说要把shadowsocksr-speed_win.py 和gui-config.json放在同一个文件夹

**Comment by 1072379816** [comment]
我想知道一台电脑正常操作流程是什么啊，cmd打开之后怎么弄

**Comment by mobier** [comment]
```
cd ../
python shadowsocksr-speed_win.py gui-config.json
```

**Comment by 1072379816** [comment]
这是什么操作，不明白啊
![Uploading image.png…]()
比如说这是我刚解压了zip，把解压包放在了桌面，原封不动，接下了怎么做？
打开cmd吗？cmd怎么弄

**Comment by 1072379816** [comment]
![image](https://user-images.githubusercontent.com/49575728/56081219-6e6a7f80-5e3d-11e9-8499-85c48df14d68.png)

**Comment by mobier** [comment]
你进入到了`win`的目录,进入程序主目录执行就可以了,xxx\shadowsocksr-speed-master>

**Comment by 1072379816** [comment]
python shadowsocksr-speed_win.py， gui-config.json

这两个文件不在同一个文件夹里面可行？
为什么还是没有成功
![image](https://user-images.githubusercontent.com/49575728/56081303-65c67900-5e3e-11e9-9df8-6bc026a54928.png)

**Comment by mobier** [comment]
抱歉，我文档有些错误的地方，如果用订阅链接的话`python shadowsocksr-speed_win.py`如果要用配置文件的话`python shadowsocksr-speed_win.py gui-config.json`

**Comment by 1072379816** [comment]
你的电脑上面是怎么操作成功的？

**Comment by mobier** [comment]
```
cd C:\Users\Dell\Downloads\shadowsocksr-speed-master
python shadowsocksr-speed_win.py
url: //输入入SSR订阅链接
```

**Comment by 1072379816** [comment]
ssr订阅链接是ssr的节点链接吗

**Comment by mobier** [comment]
是的,这样的`https://www.cordcloud.cc/link/qolQX32OqVo2Euoa?mu=0`

**Comment by mobier** [comment]
这样的链接只包含了一个节点的信息`ssr://YTEyMzEyMzEyMzEyMzEyMzEyMzEyM3Rlc3Q=YTEyMzEyMzEyMzEyMzEyMzEyMzEyM3Rlc3Q=`

**Comment by 1072379816** [comment]
这个链接怎么生成的？又怎么批量操作呢

**Comment by 1072379816** [comment]
![image](https://user-images.githubusercontent.com/49575728/56081852-52b6a780-5e44-11e9-95a5-62f6b80b1a39.png)
你给我的我用了一下，变成这样而且停不下来，ssr自动闪退了，都打不开

**Comment by 1072379816** [comment]
怎么配置文件批量操作啊

**Comment by 1072379816** [comment]
是不是需要我去学Python啊Σ( ° △ °|||)︴

**Comment by 1072379816** [comment]
![image](https://user-images.githubusercontent.com/49575728/56092218-9c0e0200-5eeb-11e9-8653-08459efcaefc.png)
弄来了订阅链接，但是每个都测试不出速度，还有就是运行的时候会打开十几个ssr

**Comment by mobier** [comment]
估计是python结束进程时候吧原来的ssr客户端结束掉了,试试别启动ssr之后再启动脚本

**Comment by qilianshanlgz** [comment]
![截图_20190427122410](https://user-images.githubusercontent.com/38285844/56822162-d039d900-6882-11e9-9deb-0000ce36c11c.png)
这是什么原因？节点是好的.

**Comment by honeymaki** [comment]
作者的脾气好到我忍不住要为了留言特意注册一个账号😂😂
