### ISSUE TITLE
pip install 安装失败

### ISSUE THREAD

**Issue by wqwxxxihhjjejesssooennc** [mobier/shadowsocksr-speed#28]
![批注 2019-04-15 010459](https://user-images.githubusercontent.com/30478118/56096427-849a3d80-5f1a-11e9-8006-62371811448a.png)
计算机小白，搜索了下没找到答案，请大虾指导下，谢谢

**Comment by mobier** [comment]
.....,不是进入到python 中执行,你直接cmd然后pip install xxx
