### ISSUE TITLE
YouTube 速率测试概率性失败

### ISSUE THREAD

**Issue by womeimingzi11** [mobier/shadowsocksr-speed#3]
YouTube 速率测试，界面停留在选择分辨率的部分，不会进一步。

![default](https://user-images.githubusercontent.com/10340253/47762413-96cf4900-dcf7-11e8-8015-d9bbe41e40ff.jpg)

Terminal 显示信息如下

Message: element not interactable
  (Session info: chrome=71.0.3578.20)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.0 x86_64)

**Comment by mobier** [comment]
我也注意到这个了，增加延时可以减少出错的几率。在下一个版本会修复这个问题
