### ISSUE TITLE
大佬~  为什么我测试的节点 network都是 fail的啊~

### ISSUE THREAD

**Issue by cynzsm** [mobier/shadowsocksr-speed#31]
我是程序小白一个~靠着百度
装了 
1个python
3个pip
终于弄好了~~ 然后测试 就全是 fail ~~不甘心啊~~

麻烦帮忙看看是什么情况~
 订阅等下发你邮箱

**Comment by zleehomc** [comment]
同 所有节点都是fail

**Comment by cynzsm** [comment]
但是 确实能用 对吧~~

寒亦唱 <notifications@github.com> 于2019年4月24日周三 上午1:09写道：

**Comment by cynzsm** [comment]
可以的话 加我tg     https://t.me/cynzsm

G Min <cynzsm@gmail.com> 于2019年4月24日周三 上午8:22写道：

**Comment by mobier** [comment]
@cynzsm 你发我的节点没问题啊,只是特别慢

**Comment by zleehomc** [comment]
有邮箱么 能测试下我的么

**Comment by mobier** [comment]
@zleehomc vxxwej@gmail.com

**Comment by cynzsm** [comment]
明天我再试试

在 2019年4月24日星期三，mobier <notifications@github.com> 写道：

**Comment by cynzsm** [comment]
老大 还是不行啊~
[IMG]http://thumbs2.imagebam.com/f1/47/01/57f0f21204554994.jpg[/IMG][/URL] 

是不是win7 的关系啊？？我看 ip.sb  还有speedtest.net 都可以连接的啊~

**Comment by qilianshanlgz** [comment]
为何我的测试结果也是：network：Fail 但是节点都是可用的

**Comment by qilianshanlgz** [comment]
为何我的测试结果也是：network：Fail 但是节点都是可用的

**Comment by mobier** [comment]
我觉得是win的缘故,我在看看

**Comment by cynzsm** [comment]
等你 大佬~~~

**Comment by LongStudy** [comment]
我上周在ubuntu环境下测试network正常，现在也都是fail了，我猜测是speedtest api改了

**Comment by vinll** [comment]
win10 可ping通 network均fail

**Comment by adamvinson** [comment]
同楼主

**Comment by EuropeanWithSSR** [comment]
似乎是ssr不能代理cmd引起的问题，但我不知道怎么解决。
用powershell也是同样的问题。
————————————————————
我傻了，把ssr调成pac或者直连模式就好

**Comment by Audacias** [comment]
> 似乎是ssr不能代理cmd引起的问题，但我不知道怎么解决。
> 用powershell也是同样的问题。
> ————————————————————
> 我傻了，把ssr调成pac或者直连模式就好

win10下，直连，cmd单独运行speedtest.py正常; 挂ssr设为全局，单独运行speedtest.py就不正常了，提示如下：
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: urlopen error _ssl.c:1039: The handshake operation timed out

感觉和主程序测速fail有关？而且我不用ssr，用sstap来挂全局代理，speedtest.py就能正常工作测出代理节点的带宽。

然后我又在虚拟机上装了最新版ubuntu，测速还是和win10一样都是fail，只能测出ip和本地ping，ping上下行什么的都是0，节点明明都可用的。

**Comment by mobier** [comment]
@Audacias 确实在原本配置中为全局模式存在问题，然后ubuntu版本还是fail的话能确定的是不是程序的问题，win版本我更新了一个版本试试？
