### ISSUE TITLE
win10不能运行

### ISSUE THREAD

**Issue by ianEros** [mobier/shadowsocksr-speed#34]
![TIM截图20190507141911](https://user-images.githubusercontent.com/35248216/57276100-1e48ab00-70d3-11e9-84d6-a0afceac07ba.png)
查了一下说是
![image](https://user-images.githubusercontent.com/35248216/57276182-5d76fc00-70d3-11e9-94df-7bedfc2ce57f.png)
而win10的  Xvfb 是一个headless display server(不太明白 大概是不兼容的意思?)
(原谅我一个c++程序员..实在不会p...)

**Comment by mobier** [comment]
这个是用来模拟浏览器去测速youtube的速度的函数,但是pyvirtualdisplay只支持unix在win上无法使用,chrome的无头模式也不好用,所以在win版本的测速工具中移除了这个youtube测速的选项
