### ISSUE TITLE
Youtube 测速问题

### ISSUE THREAD

**Issue by whalebluevpn** [mobier/shadowsocksr-speed#37]
<img width="892" alt="Snipaste_2019-05-19_10-57-51" src="https://user-images.githubusercontent.com/46555385/57977171-36022680-7a25-11e9-9fa0-7841eb0bbcce.png">
CentOS 7 上测试的，会是什么原因？

**Comment by mobier** [comment]
可以把浏览器的语言选择为中文吗,我没有做英文的适配
