### ISSUE TITLE
能够提供一个windows下也能使用的版本么？

### ISSUE THREAD

**Issue by cc9014** [mobier/shadowsocksr-speed#4]
如题

**Comment by womeimingzi11** [comment]
在 Windows 开启 Linux Subsystem 是否可以运行呢？

**Comment by mobier** [comment]
shadowsocks的daemon只支持unix,我看看怎么二次开发shadowsocks传参并启动就可以支持Win了

**Comment by cc9014** [comment]
> 
> 
> 在 Windows 开启 Linux Subsystem 是否可以运行呢？

已经开启了，无法运行 :(

就等作者的好消息了~

**Comment by dubstep1212** [comment]
请问centos怎么用

**Comment by cc9014** [comment]
好吧，我又来请教了 :(
`Traceback (most recent call last):
  File "shadowsocksr-speed_win.py", line 186, in <module>
    close_ssr()
  File "shadowsocksr-speed_win.py", line 151, in close_ssr
    subprocess.call('taskkill /f /im ShadowsocksR-dotnet4.0.exe',stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'taskkill /f /im ShadowsocksR-dotnet4.0.exe'`
不明白什么意思，我也下载并打开了ShadowsocksR-dotnet4.0.exe，需要添加到环境变量中？
 还是希望作者 @mobier   能够解答一下，万分感谢。（怎么issue没法重新打开了>.<）

**Comment by mobier** [comment]
@cc9014 看起来视乎是没有找到ssr的进程无法结束,什么系统,在cmd下执行'taskkill /f /im ShadowsocksR-dotnet4.0.exe' 有啥回显

**Comment by cc9014** [comment]
@mobier 我错了，我用的linux subsystem难怪跑不起来……
下载安装了win版python3，用cmd命令成功跑起来了 :)
使用一切正常，感谢~
