### ISSUE TITLE
测试结果导出的需求

### ISSUE THREAD

**Issue by reki-cool** [mobier/shadowsocksr-speed#47]
我这里有一个想法，就是我有非常大量的SSR链接，可否直接测试这些SSR链接，而不是通过订阅链接来测试，然后可以导出结果，存到我的数据库中，而不是直接直观的显示在屏幕上

**Comment by reki-cool** [comment]
补充：我极少在Win下使用，平时的环境都是Ubuntu，所以其它的一些测速工具都不适合我，我非常期待当前这个工具能够加入这个功能。

**Comment by mobier** [comment]
普通用户没有这个需求~自己二次开发就可以啦

**Comment by reki-cool** [comment]
:sob::sob::sob::sob::sob::sob::sob::sob::sob::sob::sob:

**Comment by reki-cool** [comment]
好吧 ，我尝试一下二次开发

**Comment by mobier** [comment]
https://github.com/NyanChanMeow/SSRSpeed
这个工具可以导出测速结果,看起来特别符合你的需求

**Comment by reki-cool** [comment]
> https://github.com/NyanChanMeow/SSRSpeed
> 这个工具可以导出测速结果,看起来特别符合你的需求

太棒啦，谢谢！:satisfied::satisfied::satisfied::satisfied:
