### ISSUE TITLE
windows下无法运行

### ISSUE THREAD

**Issue by YouHaveGone** [mobier/shadowsocksr-speed#48]
Traceback (most recent call last):
  File "shadowsocksr-speed_win.py", line 8, in <module>
    import ParseSsr #https://www.jianshu.com/p/81b1632bea7f
ModuleNotFoundError: No module named 'ParseSsr'

不知是何原因，求解

**Comment by mobier** [comment]
进入程序目录  (cd C:\Users\Dell\Downloads\shadowsocksr-speed-master)
