### ISSUE TITLE
mac测速无数值仅显示success

### ISSUE THREAD

**Issue by eyeball0704** [mobier/shadowsocksr-speed#57]
mac os 10.14.6 一开始报证书无效，加入ssl引入后可以解析订阅显示菜单
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

1、all test
  File "shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/Users/xuyy/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/Users/xuyy/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/Users/xuyy/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/Users/xuyy/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/Users/xuyy/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/Users/xuyy/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/Users/xuyy/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

安装 brew install libsodium 后不报错了

但是ip和数值均显示为空
           name             | ip | localPing | ping | upload | download | youtube | network |
+-------------------------------+----+-----------+------+--------+----------+---------+---------+
|   香港3-阿里云-流量×1.9 [单]  |    |     0     |  0   |   0    |    0     |    0    | Success |
|   香港2-阿里云-流量×1.9 [单]  |    |     0     |  0   |   0    |    0     |    0    | Success |
|     香港1-家宽-流量×1 [单]    |    |     0     |  0   |   0    |    0     |    0    | Success |
|    韩国1-CN2-流量×3.9 [单]    |    |     0     |  0   |   0    |    0     |    0    | Success |
| 过期时间：2019-08-16 20:34:21 |    |     0     |  0   |   0    |    0     |    0    |   pass  |
|    美国3-洛杉矶-流量×1 [单]   |    |     0     |  0   |   0    |    0     |    0    | Success |
|  美国2-ST机房-流量×0.01 [单]  |    |     0     |  0   |   0    |    0     |    0    | Success |
|    美国1-CN2GIA-流量×1 [单]   |    |     0     |  0   |   0    |    0     |    0    | Success |
|    深港2-可看nf-流量×1 [单]   |    |     0     |  0   |   0    |    0     |    0    | Success |
| 深港1-CN2可看nf-流量×2.9 [单] |    |     0     |  0   |   0    |    0     |    0    | Success |
| 沪日1-CN2可看nf-流量×1.9 [单] |    |     0     |  0   |   0    |    0     |    0    | Success |
|  日本2-直连东京-流量×1.9 [单] |    |     0     |  0   |   0    |    0     |    0    | Success |
|  日本1-直连东京-流量×1.9 [单] |    |     0     |  0   |   0    |    0     |    0    | Success |
|    新加坡2-直连-流量×1 [单]   |    |     0     |  0   |   0    |    0     |    0    | Success |
|   新加坡1-阿里云-流量×1 [单]  |    |     0     |  0   |   0    |    0     |    0    | Success |
|     台湾1-家宽-流量×1 [单]    |    |     0     |  0   |   0    |    0     |    0    |   pass  |
|    剩余流量：42.31% 25.38GB   |    |     0     |  0   |   0    |    0     |    0    |   pass  |
|   中国1-回国线路-流量×1 [单]  |    |     0     |  0   |   0    |    0     |    0    |   pass  |
+-------------------------------+----+-----------+------+--------+----------+---------+---------+
![Uploading 屏幕快照 2019-08-07 01.29.37.png…]()

all test 全部为fail
报错
**could not convert string to float:** 
+-------------------------------+----+-----------+------+--------+----------+---------+---------+
| 过期时间：2019-08-16 20:34:21 |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
| 沪日1-CN2可看nf-流量×1.9 [单] |    |     0     |  0   |   0    |    0     |    0    |   Fail  |
|  日本2-直连东京-流量×1.9 [单] |    |     0     |  0   |   0    |    0     |    0    |   Fail  |
|  日本1-直连东京-流量×1.9 [单] |    |     0     |  0   |   0    |    0     |    0    |   Fail  |
|    新加坡2-直连-流量×1 [单]   |    |     0     |  0   |   0    |    0     |    0    |   Fail  |
|   新加坡1-阿里云-流量×1 [单]  |    |     0     |  0   |   0    |    0     |    0    |   Fail  |
|     台湾1-家宽-流量×1 [单]    |    |     0     |  0   |   0    |    0     |    0    |   Fail  |
|    剩余流量：42.31% 25.38GB   |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|   中国1-回国线路-流量×1 [单]  |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
+-------------------------------+----+-----------+------+--------+----------+---------+---------+

**Comment by mobier** [comment]
订阅链接发我邮箱我看看
