### ISSUE TITLE
老大~ win 显示fail的问题解决了，又有新的想法了

### ISSUE THREAD

**Issue by cynzsm** [mobier/shadowsocksr-speed#58]
就是 很多fail 的节点，要是一个一个的删除有点太浪费时间了，尤其是节点超过100个的时候。
老大能不能想办法把 fail的节点 全删除了啊？

**Comment by mobier** [comment]
只显示成功节点吗？

**Comment by keke270** [comment]
这个想法很好，直接测试所有节点，排除不能链接的，导出排序网速最快并且正确连接的，有些机场挂的节点很多，手动找正确节点稍微有点麻烦

**Comment by mobier** [comment]
现在默认是根据youtube 排序的，win根据speedtest的带宽排序，需要改进哪里？

**Comment by keke270** [comment]
好像没啥需要改进的。测速完删除无法连接的节点就差不多，然后导出正确节点。毕竟一般用这个都只是测速，实际使用还是挂软件或者路由器上。
