### ISSUE TITLE
win报错了

### ISSUE THREAD

**Issue by jamesfu1978** [mobier/shadowsocksr-speed#59]
File "shadowsocksr-speed_win.py", line 3, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

**Comment by jamesfu1978** [comment]
File "shadowsocksr-speed_win.py", line 3, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

**Comment by mobier** [comment]
pip install PySocks prettytable requests

**Comment by jamesfu1978** [comment]
> pip install PySocks prettytable requests

搞定了，感谢。没装 prettytable 模块，我该自己谷歌的。。。
