### ISSUE TITLE
能否说下延迟方面是怎么测速的

### ISSUE THREAD

**Issue by orange723** [mobier/shadowsocksr-speed#65]
py菜鸟，想自己写一个测速，只看延迟时间  感谢

**Comment by mobier** [comment]
emmm,不是写了ping吗

**Comment by orange723** [comment]
额，真的只有ping嘛，我想的不应该是代理这个地址然后 去测延迟

mobier <notifications@github.com>于2019年9月3日 周二下午7:33写道：

**Comment by mobier** [comment]
分两个，一个是本地到服务器的延迟，另外一个是代理后speedtest返回的延迟

**Comment by orange723** [comment]
待我在学一学在看吧，感谢

mobier <notifications@github.com>于2019年9月4日 周三下午9:52写道：
