### ISSUE TITLE
RequestsDependencyWarning: urllib3  or chardet  doesn't match a supported version

### ISSUE THREAD

**Issue by joshatt** [mobier/shadowsocksr-speed#66]
linux好难, 好不容易VMWARE装上ubuntu安装各种包排除了各种问题, 可以用了. 不过测试了一个订阅, all tests, 发现:
结果只有两种: timeout和fail------
timeout的, 之前的各项(ping和上传下载等)都有数值, 但youtube是1.
fail的youtube是0
试了无论主机(win7)挂代理还是不挂, 都是如此.

说明什么?

**Comment by mobier** [comment]
感觉是节点太慢了，network是通的吗
