### ISSUE TITLE
请教有了测速之后能不能自动切换线路

### ISSUE THREAD

**Issue by zfk513** [mobier/shadowsocksr-speed#71]
由于周年大庆
不稳定 所以订阅的账号需要自动切换 
但是手动换还是挺烦的
负载均衡感觉上还不如一直用一个稳定的系统 ,SSR没研究过,SS的负载均衡 和随机的效果也没啥区别
现在只有SSR的链接了
其他选项:V2Rray,试了下,还没连接成功,尴尬
其他因素:家里是辣鸡长城宽带,所以测速切换功能还是挺需要的,
不知道UP主是否有这方面的经验和思路,请赐教,谢谢

**Comment by mobier** [comment]
改改能实现，这个工具实际开了6667端口然后用这个端口测速，上网同理
