### ISSUE TITLE
不能解析SSR链接

### ISSUE THREAD

**Issue by blurm** [mobier/shadowsocksr-speed#73]
订阅链接是ssrcloud的，不清楚是不是和机场自己的设置有关

`不能解析SSR链接: MjAwMToxOWYwOmIwMDE6M2EwOjU0MDA6MmZmOmZlMzU6MzkyNjo0MzI5NzpvcmlnaW46cmM0LW1kNTpodHRwX3NpbXBsZTpOR2c1YUVGUi8_b2Jmc3BhcmFtPVpHOTNibXh2WVdRdWQybHVaRzkzYzNWd1pHRjBaUzVqYjIwJnByb3RvcGFyYW09JnJlbWFya3M9NTRtNTVxNks1Wnl3NVl5NjU1U282WUNVNklxQzU0SzU2TC1lNW82bDZMNkQ1b1dpSU9Xd2otZVp2ZWVVcU9hSXQtaXZ0LVdMdi1TOXYtZVVxT2F0cE9pS2d1ZUN1ZWluZ3VlY2l5QlpiM1YwZFdKbElPV0tvT2FMdi1Xa3B5QnBjSFkySUROSFluQnpJREhsZ0kwJmdyb3VwPWMzTnlZMnh2ZFdR
不能解析SSR链接: MjQwMDo2MTgwOjEwMDpkMDo6MjQ6MTAwMTo0MzI5NzpvcmlnaW46cmM0LW1kNTpodHRwX3NpbXBsZTpOR2c1YUVGUi8_b2Jmc3BhcmFtPVpHOTNibXh2WVdRdWQybHVaRzkzYzNWd1pHRjBaUzVqYjIwJnByb3RvcGFyYW09JnJlbWFya3M9NTRtNTVxNks1Wnl3NVl5NjU1U282WUNVNklxQzU0SzU2TC1lNW82bDZMNkQ1b1dpSU9Xd2otZVp2ZWVVcU9hSXQtaXZ0LVdMdi1TOXYtZVVxT2F0cE9pS2d1ZUN1ZWluZ3VlY2l5QlpiM1YwZFdKbElPV05zT1c2cGlCcGNIWTJJRE5IWW5CeklESGxnSTAmZ3JvdXA9YzNOeVkyeHZkV1E
不能解析SSR链接: MmEwMzpiMGMwOjM6ZTA6OjEyZTozMDAxOjQzMjk3Om9yaWdpbjpyYzQtbWQ1Omh0dHBfc2ltcGxlOk5HZzVhRUZSLz9vYmZzcGFyYW09Wkc5M2JteHZZV1F1ZDJsdVpHOTNjM1Z3WkdGMFpTNWpiMjAmcHJvdG9wYXJhbT0mcmVtYXJrcz01NG01NXE2SzVaeXc1WXk2NTVTbzZZQ1U2SXFDNTRLNTZMLWU1bzZsNkw2RDVvV2lJT1d3ai1lWnZlZVVxT2FJdC1pdnQtV0x2LVM5di1lVXFPYXRwT2lLZ3VlQ3VlaW5ndWVjaXlCWmIzVjBkV0psSU9XLXQtV2J2U0JwY0hZMklETkhZbkJ6SURIbGdJMCZncm91cD1jM055WTJ4dmRXUQ
不能解析SSR链接: MmEwMzpiMGMwOjM6ZDA6OjdjZjplMDAxOjQzMjk3Om9yaWdpbjpyYzQtbWQ1Omh0dHBfc2ltcGxlOk5HZzVhRUZSLz9vYmZzcGFyYW09Wkc5M2JteHZZV1F1ZDJsdVpHOTNjM1Z3WkdGMFpTNWpiMjAmcHJvdG9wYXJhbT0mcmVtYXJrcz01NG01NXE2SzVaeXc1WXk2NTVTbzZZQ1U2SXFDNTRLNTZMLWU1bzZsNkw2RDVvV2lJT1d3ai1lWnZlZVVxT2FJdC1pdnQtV0x2LVM5di1lVXFPYXRwT2lLZ3VlQ3VlaW5ndWVjaXlCWmIzVjBkV0psSU9XLXQtV2J2U0JwY0hZMklPV0lodWExZ1NBelIySndjeUF4NVlDTiZncm91cD1jM055WTJ4dmRXUQ
不能解析SSR链接: MjQwNDo5ZWMwOjEwMDozNTdiOjAwMDA6MDAwMDowMDAwOjAwMDE6NDMyOTc6b3JpZ2luOnJjNC1tZDU6aHR0cF9zaW1wbGU6TkdnNWFFRlIvP29iZnNwYXJhbT1aRzkzYm14dllXUXVkMmx1Wkc5M2MzVndaR0YwWlM1amIyMCZwcm90b3BhcmFtPSZyZW1hcmtzPTU0bTU1cTZLNVp5dzVZeTY1NVNvNllDVTZJcUM1NEs1NkwtZTVvNmw2TDZENW9XaUlPV3dqLWVadmVlVXFPYUl0LWl2dC1XTHYtUzl2LWVVcU9hdHBPaUtndWVDdWVpbmd1ZWNpeUJaYjNWMGRXSmxJT2UtanVXYnZlYTBtLWFkaWVlZnRpQnBjSFkySURFd1IySndjeUF4NVlDTiZncm91cD1jM055WTJ4dmRXUQ
不能解析SSR链接: MjYwNDphODgwOjgwMDpjMTo6MTAyOmQwMDE6NDMyOTc6b3JpZ2luOnJjNC1tZDU6aHR0cF9zaW1wbGU6TkdnNWFFRlIvP29iZnNwYXJhbT1aRzkzYm14dllXUXVkMmx1Wkc5M2MzVndaR0YwWlM1amIyMCZwcm90b3BhcmFtPSZyZW1hcmtzPTU0bTU1cTZLNVp5dzVZeTY1NVNvNllDVTZJcUM1NEs1NkwtZTVvNmw2TDZENW9XaUlPV3dqLWVadmVlVXFPYUl0LWl2dC1XTHYtUzl2LWVVcU9hdHBPaUtndWVDdWVpbmd1ZWNpeUJaYjNWMGRXSmxJT2UtanVXYnZlZTZ2ZWU2cGlCcGNIWTJJT1dJaHVhMWdTQXpSMkp3Y3lBeDVZQ04mZ3JvdXA9YzNOeVkyeHZkV1E
不能解析SSR链接: MmEwZDo1NjAwOjIwOjpkMzcwOmQzMTU6NDMyOTc6b3JpZ2luOnJjNC1tZDU6aHR0cF9zaW1wbGU6TkdnNWFFRlIvP29iZnNwYXJhbT1aRzkzYm14dllXUXVkMmx1Wkc5M2MzVndaR0YwWlM1amIyMCZwcm90b3BhcmFtPSZyZW1hcmtzPTU0bTU1cTZLNVp5dzVZeTY1NVNvNllDVTZJcUM1NEs1NkwtZTVvNmw2TDZENW9XaUlPV3dqLWVadmVlVXFPYUl0LWl2dC1XTHYtUzl2LWVVcU9hdHBPaUtndWVDdWVpbmd1ZWNpeUJaYjNWMGRXSmxJT2lMc2VXYnZTQnBjSFkySUROSFluQnpJREhsZ0kwJmdyb3VwPWMzTnlZMnh2ZFdR
不能解析SSR链接: MmEwMzpiMGMwOjE6ZTA6OjJlNDo2MDAxOjQzMjk3Om9yaWdpbjpyYzQtbWQ1Omh0dHBfc2ltcGxlOk5HZzVhRUZSLz9vYmZzcGFyYW09Wkc5M2JteHZZV1F1ZDJsdVpHOTNjM1Z3WkdGMFpTNWpiMjAmcHJvdG9wYXJhbT0mcmVtYXJrcz01NG01NXE2SzVaeXc1WXk2NTVTbzZZQ1U2SXFDNTRLNTZMLWU1bzZsNkw2RDVvV2lJT1d3ai1lWnZlZVVxT2FJdC1pdnQtV0x2LVM5di1lVXFPYXRwT2lLZ3VlQ3VlaW5ndWVjaXlCWmIzVjBkV0psSU9pTHNlV2J2U0JwY0hZMklPV0lodWExZ1NBelIySndjeUF4NVlDTiZncm91cD1jM055WTJ4dmRXUQ
不能解析SSR链接: MmEwMzpiMGMwOjI6ZjA6OmQzOmEwMDE6NDMyOTc6b3JpZ2luOnJjNC1tZDU6aHR0cF9zaW1wbGU6TkdnNWFFRlIvP29iZnNwYXJhbT1aRzkzYm14dllXUXVkMmx1Wkc5M2MzVndaR0YwWlM1amIyMCZwcm90b3BhcmFtPSZyZW1hcmtzPTU0bTU1cTZLNVp5dzVZeTY1NVNvNllDVTZJcUM1NEs1NkwtZTVvNmw2TDZENW9XaUlPV3dqLWVadmVlVXFPYUl0LWl2dC1XTHYtUzl2LWVVcU9hdHBPaUtndWVDdWVpbmd1ZWNpeUJaYjNWMGRXSmxJT2lOdC1XRnNDQnBjSFkySUROSFluQnpJREhsZ0kwJmdyb3VwPWMzTnlZMnh2ZFdR
不能解析SSR链接: MjYwNDphODgwOjQwMDpkMTo6OGU4OjQwMDE6NDMyOTc6b3JpZ2luOnJjNC1tZDU6aHR0cF9zaW1wbGU6TkdnNWFFRlIvP29iZnNwYXJhbT1aRzkzYm14dllXUXVkMmx1Wkc5M2MzVndaR0YwWlM1amIyMCZwcm90b3BhcmFtPSZyZW1hcmtzPTU3Nk81WnU5NTdxOTU3cW1JR2x3ZGpZZ00wZGljSE1nTWVXQWpRJmdyb3VwPWMzTnlZMnh2ZFdR
Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 327, in <module>
    ssr_config=curses.wrapper(SelectTable)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "shadowsocksr-speed.py", line 158, in SelectTable
    x['select']=1
TypeError: 'NoneType' object does not support item assignment
`

**Comment by mobier** [comment]
感觉是和机场设置有关我直接用工具解析也是部分乱码
