### ISSUE TITLE
请问speedtest有办法单线程测试吗？

### ISSUE THREAD

**Issue by zzzop** [mobier/shadowsocksr-speed#75]

**Comment by mobier** [comment]
没明白什么意思现在就是单线程啊

**Comment by zzzop** [comment]
> 没明白什么意思现在就是单线程啊

我没表达清楚，speedtest不是有两种吗，现在用的就是单个连接这种吗
![捕获](https://user-images.githubusercontent.com/28821632/66616614-25389400-ec04-11e9-92c8-70b7a003f288.JPG)

**Comment by mobier** [comment]
把目录下的speedtest换成最新版本的然后把文件中的args.single，default=False 改为True
