### ISSUE TITLE
错误: 没有找到进程 "ShadowsocksR-dotnet4.0-speedtest.exe"。

### ISSUE THREAD

**Issue by 6a2p5l2z** [mobier/shadowsocksr-speed#76]
+--------------+----+-----------+------+--------+----------+---------+
|     name     | ip | localPing | ping | upload | download | network |
+--------------+----+-----------+------+--------+----------+---------+
| [V1] 香港08  |    |     20    |  0   |   0    |    0     |   Fail  |
| [V1] 香港07  |    |     22    |  0   |   0    |    0     |   Fail  |
| [V1] 香港06  |    |     23    |  0   |   0    |    0     |   Fail  |
| [V1] 香港05  |    |     22    |  0   |   0    |    0     |   Fail  |
| [V1] 香港04  |    |     25    |  0   |   0    |    0     |   Fail  |
| [V1] 香港03  |    |     15    |  0   |   0    |    0     |   Fail  |
| [V1] 香港02  |    |     30    |  0   |   0    |    0     |   Fail  |
| [V1] 香港01  |    |     13    |  0   |   0    |    0     |   Fail  |
|  [V1] 韩国2  |    |    187    |  0   |   0    |    0     |   Fail  |
|  [V1] 韩国1  |    |    101    |  0   |   0    |    0     |   Fail  |
| [V1] 美国02  |    |    192    |  0   |   0    |    0     |   Fail  |
| [V1] 美国01  |    |    160    |  0   |   0    |    0     |   Fail  |
|  [V1] 日本3  |    |     70    |  0   |   0    |    0     |   Fail  |
|  [V1] 日本2  |    |     72    |  0   |   0    |    0     |   Fail  |
|  [V1] 日本1  |    |     75    |  0   |   0    |    0     |   Fail  |
| [V1] 新加坡2 |    |     66    |  0   |   0    |    0     |   Fail  |
| [V1] 新加坡1 |    |     51    |  0   |   0    |    0     |   Fail  |
|  [V1] 台湾2  |    |     41    |  0   |   0    |    0     |   Fail  |
|  [V1] 台湾1  |    |     47    |  0   |   0    |    0     |   Fail  |
+--------------+----+-----------+------+--------+----------+---------+
错误: 没有找到进程 "ShadowsocksR-dotnet4.0-speedtest.exe"。

**Comment by mobier** [comment]
直接运行win/ShadowsocksR-dotnet4.0-speedtest.exe 可以吗
