### ISSUE TITLE
整在使用，使用过程中希望添加几个小功能进去

### ISSUE THREAD

**Issue by ao121** [mobier/shadowsocksr-speed#79]
1.希望测试结果，打印时候的添加ssr://链接，方便快速筛选出高效节点
2希望能添加导出功能，
3设置下载速度大于》多少 导出 配置文件或者ssr链接
4增加 测试时间设置
  有了这些功能，着软件就牛逼了，实现起来应该都不难。关键是使用者我 不会修改，如何作者感觉太麻烦 那希望添加功能1 就是增加一个配置或者ssr 打印。

**Comment by mobier** [comment]
这段时间比较忙，有机会在改改，感谢
